name: raftstereo
channels:
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.8.3
  - pytorch=1.8.1
  - torchvision
  - cudatoolkit=11
  - matplotlib
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - opt_einsum
  - imageio
  - scikit-image
  - p7zip
